apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-clf-infer-tutorial
  annotations:
    scenarios.ai.sap.com/description: "SAP AI Core tutorial scenario"
    scenarios.ai.sap.com/name: "image-clf-tutorial-scenario"
    executables.ai.sap.com/description: "Inference executable for image classification"
    executables.ai.sap.com/name: "image-clf-infer-tutorial-exec"
  labels:
    scenarios.ai.sap.com/id: "image-clf-tutorial"
    executables.ai.sap.com/id: "image-clf-infer-tutorial"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts:
      - name: imagemodel
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kfserving-container
          image: "docker.io/yoshidj/image-clf-serve:0.0.1"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.textmodel}}"
