apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-seg-infer
  annotations:
    scenarios.ai.sap.com/description: "SAP AI Core tutorial scenario"
    scenarios.ai.sap.com/name: "image-seg"
    executables.ai.sap.com/description: "Inference executable for image segmentation"
    executables.ai.sap.com/name: "image-seg-infer-exec"
  labels:
    scenarios.ai.sap.com/id: "image-seg"
    executables.ai.sap.com/id: "image-seg-infer"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts:
      - name: imagesegmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: "docker.io/YOUR_DOCKER_USERNAME/image-seg-infer:mobilenet"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.imagesegmodel}}"
