apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: image-seg-train-uXXXX
  annotations:
    scenarios.ai.sap.com/description: "SAP developers tutorial scenario"
    scenarios.ai.sap.com/name: "image-seg-uXXXX"
    executables.ai.sap.com/description: "Image segmentation training executable"
    executables.ai.sap.com/name: "image-seg-train-exec-uXXXX"
    artifacts.ai.sap.com/image-data.kind: "dataset"
    artifacts.ai.sap.com/image-model-tutorial.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "image-seg-uXXXX"
    executables.ai.sap.com/id: "image-seg-train-uXXXX"
    ai.sap.com/version: "1.0.0"
spec:
  imagePullSecrets:
    - name: docker-registry-uXXXX
  entrypoint: image-seg-sk-training
  templates:
    - name: image-seg-sk-training
      metadata:
        labels:
          ai.sap.com/resourcePlan: infer.s
      inputs:
        artifacts:
          - name: image-data
            path: /app/data/
      outputs:
        artifacts:
          - name: image-model-tutorial
            path: /app/model
            globalName: image-model-tutorial
            archive:
              none: {}
      container:
        image: "docker.io/YOUR_DOCKER_USERNAME/image-seg-train:mobilenet"
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - >
            set -e && echo "---Start Training---" && python /app/src/train.py && ls -lR /app/model && echo "---End Training---"
